Repository Future-Gadgets-Labs/PhoneWave, pull requests merged in 2022-04, with the labels that each got.

#11 Rank System Implementation Start
  app/config.py
  app/database/database.py
  app/database/models/member.py
  app/database/ranks/__init__.py
  app/database/ranks/baserank.py
  app/database/ranks/rank5.py
  app/modules/ranksystem/__init__.py
  app/modules/ranksystem/ranksystem.py
Labels: enhancement

#12 WIP: New 'profile' and 'announcement' commands
  .env.example
  README.md
  app/cache.py
  app/cli.py
  app/client.py
  app/config.py
  app/database/__init__.py
  app/database/database.py
  app/database/models/announcements.py
  app/database/models/guild.py
  app/database/models/member.py
  app/modules/announcements/__init__.py
  app/modules/announcements/announcements.py
  app/modules/core/error_handler.py
  app/modules/info/ping.py
  app/modules/prefix/__init__.py
  app/modules/prefix/prefix.py
  app/modules/profile/__init__.py
  app/modules/profile/profile.py
  app/modules/ranksystem/__init__.py
  app/modules/ranksystem/ranksystem.py
  app/modules/role/__init__.py
  app/modules/role/role.py
  app/modules/say/__init__.py
  app/modules/say/say.py
  app/utilities/emoji.py
  app/utilities/handlers.py
  app/utilities/logger.py
  docker-compose.yml
  requirements.txt
Labels: feature, help wanted

#14 Added two example tests for Pytest and some fixes (+Added MongoMock)
  app/database/database.py
  app/database/models/guild.py
  app/database/models/member.py
  app/tests/conftest.py
  app/tests/ranksystem/__init__.py
  app/tests/ranksystem/xp_test.py
  app/tests/utilities/nick_test.py
  app/utilities/labmem.py
  requirements.txt
Labels: bug, feature, test

#15 Rank implementation + New Tests
  app/config.py
  app/database/models/__init__.py
  app/database/models/rank.py
  app/database/ranks/__init__.py
  app/database/ranks/baserank.py
  app/database/ranks/rank5.py
  app/modules/ranksystem/ranksystem.py
  app/tests/conftest.py
  app/tests/ranksystem/rank_test.py
  app/tests/ranksystem/xp_test.py
  app/types/discord.py
  app/utilities/finders.py
Labels: feature, test

#17 Testcord Patch Merge
  app/tests/conftest.py
  app/tests/ranksystem/rank_test.py
  app/tests/ranksystem/xp_test.py
  requirements.txt
  vendor/discord/ext/test/__init__.py
  vendor/discord/ext/test/_types.py
  vendor/discord/ext/test/backend.py
  vendor/discord/ext/test/callbacks.py
  vendor/discord/ext/test/factories.py
  vendor/discord/ext/test/runner.py
  vendor/discord/ext/test/state.py
  vendor/discord/ext/test/utils.py
  vendor/discord/ext/test/verify.py
  vendor/discord/ext/test/websocket.py
  vendor/testcord-0.0.1.dist-info/INSTALLER
  vendor/testcord-0.0.1.dist-info/LICENSE
  vendor/testcord-0.0.1.dist-info/METADATA
  vendor/testcord-0.0.1.dist-info/RECORD
  vendor/testcord-0.0.1.dist-info/REQUESTED
  vendor/testcord-0.0.1.dist-info/WHEEL
  vendor/testcord-0.0.1.dist-info/top_level.txt
Labels: bug, feature, test

#18 CI workflows to run Pytest and build Docker images
  .dockerignore
  .github/workflows/docker.yml
  .github/workflows/pytest.yml
  dockerfile
  requirements.txt
Labels: feature

#19 Remove testcord from dependencies
  Pipfile
  Pipfile.lock
  README.md
  requirements.txt
Labels: test

#21 Updated Member, removed testcord dependency, updated CONTRIBUTING
  CONTRIBUTING.md
  Pipfile
  Pipfile.lock
  app/database/models/guild.py
  app/database/models/member.py
  app/modules/ranksystem/ranksystem.py
Labels: documentation, feature

#22 Update Pipfile.lock
  Pipfile
  Pipfile.lock
Labels: test

#23 Mock Redis cache/server implementation
  app/cache.py
  app/client.py
  app/database/cache_server.py
  app/tests/conftest.py
  vendor/mockredis/__init__.py
  vendor/mockredis/mockserver.py
  vendor/mockredis/tests/__init__.py
  vendor/mockredis/tests/conftest.py
  vendor/mockredis/tests/func_test.py
Labels: feature, test
